spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_engine
    username: postgres
    password: testtest
  liquibase:
    change-log: classpath:db.changelog-master.yaml
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: Europe/Moscow
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        globally_quoted_identifiers: true
  http:
    encoding:
      charset: UTF-8
      enabled: true